name: Build

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  lint:
    steps:
      - run:
          name: Lint files
          command: |
            yarn lint

  typescript:
    steps:
      - run:
          name: Typescript checking
          command: |
            yarn typescript
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: |
          yarn
      - name: Build Android
        run: |
          cd example/android
          ./gradlew build
      # - name: Install Cocoapods
      #   run: sudo gem install -n /usr/local/bin cocoapods
      # - name: Install Pods
      #   run: |
      #     cd example/ios
      #     pod install
      # - name: Build iOS
      #   run: |
      #     xcodebuild -scheme MyApp -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.0'
