name: Build

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Build Android
        run: |
          cd ../android
          ./gradlew build
      - name: Install Cocoapods
        run: sudo gem install -n /usr/local/bin cocoapods
      - name: Install Pods
        run: |
          cd example/ios
          pod install
      - name: Build iOS
        run: |
          xcodebuild -scheme MyApp -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.0'
