name: Publish

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    container:
      image: klimandrew/node-pnpm

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build
        run: pnpm run build

      - name: Create package tarball
        run: |
          version=$(jq -r .version package.json)
          pnpm pack --out-dir . --filename "react-native-rtmp-publisher-$version.tgz"

      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          version=$(jq -r .version package.json)
          pnpm publish "react-native-rtmp-publisher-$version.tgz" --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
