name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    container:
      image: klimandrew/node-pnpm

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm install

      - name: Create package tarball
        run: pnpm pack

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          version=$(jq -r .version package.json)
          pnpm publish "react-native-publisher-$version.tgz" --access public

      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "react-native-publisher-*.tgz"
